
steps:
  # build container images be
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
            '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-be-docker-repo/my-app-be:${SHORT_SHA}', './be']

  #  # Docker push to Google Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push',  '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-be-docker-repo/my-app-be:${SHORT_SHA}']

   # build container images fe
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
            '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-fe-docker-repo/my-app-fe:${SHORT_SHA}', './frontend']

  #  # Docker push to Google Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}']

    # package helm chart
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Update values
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      sed -e "s/PROJECT_ID/${PROJECT_ID}/g" -e "s/IMAGE_TAG/${SHORT_SHA}/g" -e "s/LOCATION/${_LOCATION}/g" infra/k8s/helm/values.yaml 
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Push chart
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      helm repo list && \
      helm package ./infra/k8s/helm --destination ./package --version ${SHORT_SHA} && \
      gcloud auth configure-docker ${_LOCATION}-docker.pkg.dev && \
      helm push ./package/my-app-${SHORT_SHA}.tgz oci://${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-helm-repo

substitutions:
  _LOCATION: us-east4 # us-east1
# Store images in Google Artifact Registry 
images:
  - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-be-docker-repo/my-app-be:${SHORT_SHA}
  - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-fe-docker-repo/my-app-fe:${SHORT_SHA}


# Deploy pipeline (Do manually for now)
    # install helm
    # install/upgrade helm chart