
steps:
  # build container images be
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
            '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-be-docker-repo/my-app-be:${SHORT_SHA}', './be']

  #  # Docker push to Google Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push',  '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-be-docker-repo/my-app-be:${SHORT_SHA}']

   # build container images fe
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
            '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-fe-docker-repo/my-app-fe:${SHORT_SHA}', './frontend']

  #  # Docker push to Google Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}']

    # package helm chart
  - name: 'alpine/helm'
    args: ['package', './infra/k8s/helm', '--destination', './package', '--set', 'image.tag=${SHORT_SHA}', '--version', '${SHORT_SHA}']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  # push helm chart to repo
  - name: 'alpine/helm'
    args: ['push', './package/my-app-${SHORT_SHA}.tgz', 'oci://${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-helm-repo']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
substitutions:
  _LOCATION: us-central1 # us-east1
# Store images in Google Artifact Registry 
images:
  - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-be-docker-repo/my-app-be:${SHORT_SHA}
  - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-app-fe-docker-repo/my-app-fe:${SHORT_SHA}


# Deploy pipeline (Do manually for now)
    # install helm
    # install/upgrade helm chart