{{- if .Values.backendConfig.create }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-app-backendconfig-be
spec:
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 5
    port: {{ .Values.beService.port }}
    type: HTTP
    requestPath: /api/health
{{- end }}
