apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.beService.name}}
spec:
  type: {{ .Values.beService.type }}
  selector:
    app: {{ .Values.beDeployment.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.beService.port }}
      {{ with index .Values.beDeployment.ports 0 }}
      targetPort: {{ .containerPort }}
      {{ end }}
