{{- if .Values.backendConfig.create }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-app-backendconfig-fe
spec:
  cdn:  
    enabled: true
    requestCoalescing: true
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 5
    port: {{ .Values.feService.port }}
    type: HTTP
    requestPath: /health
{{- end }}
