apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-fe-deployment
  labels:
    name: my-app-fe
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.feDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.feDeployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.feDeployment.labels.app }}
    spec:
      containers:
        - image: "{{ .Values.feDeployment.image.repository }}:{{ .Values.deploymentCommon.image.tag }}"
          name: my-app-fe-container
          imagePullPolicy: {{ .Values.deploymentCommon.image.pullPolicy }}
          ports:
            - containerPort: {{  .Values.feDeployment.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.feDeployment.resources.requests.cpu }}
              memory: {{ .Values.feDeployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.feDeployment.resources.limits.cpu }}
              memory: {{ .Values.feDeployment.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: {{  .Values.feDeployment.probePath }}
              port: {{  .Values.feDeployment.containerPort }}
            failureThreshold: 3
            periodSeconds: 20
            initialDelaySeconds: 25
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: {{  .Values.feDeployment.probePath }}
              port: {{  .Values.feDeployment.containerPort }}
            failureThreshold: 3
            periodSeconds: 20
            initialDelaySeconds: 25
            successThreshold: 1
            timeoutSeconds: 5
      dnsPolicy: {{ .Values.deploymentCommon.dnsPolicy }}
      restartPolicy: {{ .Values.deploymentCommon.restartPolicy }}