# https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs
{{- if .Values.ssl.create }}
{{- with .Values.ssl }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .name }}
spec:
  domains:
    {{- toYaml .domains | nindent 4 }}
{{- end }}
{{- end }}
