# https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs
{{- if .Values.ssl.create }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ssl.name }}
  namespace: {{ .Values.namespace }}
spec:
  domains:
    {{- toYaml .Values.ssl.domains | nindent 4 }}
{{- end }}
