nameOverride: ""
fullnameOverride: ""

deploymentCommon:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  image:
    tag: latest
    pullPolicy: Always
  nodeSelector: {}

feDeployment:
  replicas: 2
  labels:
    app: my-app-fe
  ports:
    - containerPort: 80
  image:
    repository: vyathartha/my-app-fe
  resources: # The resource requests and limits for the container
    requests:
      cpu: "250m"
      memory: "200Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"

feService:
  name: my-app-fe-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  type: ClusterIP
  port: 8081

beDeployment:
  replicas: 2
  labels:
    app: my-app-be
  ports:
    - containerPort: 8080
  image:
    repository: vyathartha/user-app
  resources: # The resource requests and limits for the container
    requests:
      cpu: "250m"
      memory: "150Mi"
    limits:
      cpu: "400m"
      memory: "400Mi"

beService:
  name: my-app-be-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  type: ClusterIP
  port: 8080

ingress:
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: "global-ingress"
    # networking.gke.io/managed-certificates: networking-managed-cert
    # networking.gke.io/v1beta1.FrontendConfig: networking-fc
    kubernetes.io/ingress.class: gce
  includeDefaultBackend: false
  rules:
    - http:
        paths:
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ .Values.beService.name }}"
                port: "{{ .Values.beService.port }}"
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ .Values.feService.name }}"
                port: "{{ .Values.feService.port }}"

