apiVersion: v1
kind: Service
metadata:
  name: my-app-fe-service
  labels:
    service: my-app-fe-service
spec:
  type: ClusterIP
  selector:
    app: my-app-fe
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
