/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/~__root'
import { Route as IndexImport } from './pages/~index'
import { Route as PortfolioRouteImport } from './pages/~portfolio/~route'
import { Route as AdminRouteImport } from './pages/~admin/~route'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioRouteRoute = PortfolioRouteImport.update({
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRoute
    }
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AdminRouteRoute,
  PortfolioRouteRoute,
  IndexRoute,
])

/* prettier-ignore-end */
