/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/~__root'
import { Route as PortfolioRouteImport } from './pages/~portfolio/~route'
import { Route as HealthImport } from './pages/~health'
import { Route as BlogsRouteImport } from './pages/~blogs/~route'
import { Route as AdminRouteImport } from './pages/~admin/~route'
import { Route as IndexImport } from './pages/~index'

// Create/Update Routes

const PortfolioRouteRoute = PortfolioRouteImport.update({
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const HealthRoute = HealthImport.update({
  path: '/health',
  getParentRoute: () => rootRoute,
} as any)

const BlogsRouteRoute = BlogsRouteImport.update({
  path: '/blogs',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/blogs': {
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRoute
    }
    '/health': {
      preLoaderRoute: typeof HealthImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminRouteRoute,
  BlogsRouteRoute,
  HealthRoute,
  PortfolioRouteRoute,
])

/* prettier-ignore-end */
